=== srzeppa/XML/lab3/lab3dtd2.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT uczelnia   (nazwa, rektor, prorektor, prorektor, 
                      wydzial, wydzial+, katedra*,biblioteka?)>

<!ELEMENT nazwa      (#PCDATA)>
<!ELEMENT rektor     (tytul, imie, nazwisko)>
<!ELEMENT prorektor  (tytul, imie, nazwisko)>
<!ELEMENT imie       (#PCDATA)>
<!ELEMENT nazwisko   (#PCDATA)>
<!ELEMENT tytul      (#PCDATA)>
<!ELEMENT wydzial    (nazwa, dziekan, prodziekan*, instytut+, kierunek+)>
<!ELEMENT dziekan    (imie, nazwisko, tytul)>
<!ELEMENT prodziekan (imie, nazwisko, tytul)>
<!ELEMENT instytut   (nazwa, dyrektor)>
<!ELEMENT dyrektor   (tytul, imie, nazwisko)>
<!ELEMENT kierunek   (nazwa, kurs+)>
<!ELEMENT kurs       (nazwa, opis, forma*, limit)>
<!ELEMENT opis       (#PCDATA)>
<!ELEMENT forma      (#PCDATA)>
<!ELEMENT limit     (#PCDATA)>
<!ELEMENT katedra    (nazwa, dyrektor)>
<!ELEMENT biblioteka (#PCDATA)>

=== srzeppa/XML/lab3/zad1.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE uczelnia SYSTEM "lab3dtd2.dtd">

<uczelnia>
	<nazwa>Uniwersytet Gdański</nazwa>
	
		<rektor>
			<tytul>profesor</tytul>
			<imie>Avxzfsfs</imie>
			<nazwisko>Casdadas</nazwisko>
		</rektor>
		
		<prorektor>
			<tytul>profesor</tytul>
			<imie>Acascsds</imie>
			<nazwisko>Józek</nazwisko>
		</prorektor>
		
		<prorektor>
			<tytul>profesor</tytul>
			<imie>ziomek</imie>
			<nazwisko>ziomeczek</nazwisko>
		</prorektor>
		
		<wydzial>
			<nazwa>Matematyki</nazwa>
			
			<dziekan>
				<imie>Acfasdas</imie>
				<nazwisko>Adsadas</nazwisko>
				<tytul>profesor</tytul>
			</dziekan>
			
			<prodziekan>
				<imie>Adsavdasv</imie>
				<nazwisko>Afasvcvcxds</nazwisko>
				<tytul>Dsadsa</tytul>
			</prodziekan>
			
		<instytut>
			<nazwa>Geometrii</nazwa>
			
			<dyrektor>
				<tytul>profesor</tytul>
				<imie>Marceli</imie>
				<nazwisko>Kowalczyk</nazwisko>
			</dyrektor>
		</instytut>
		
		<kierunek>
			<nazwa>Matematyka</nazwa>
			<kurs>
				<nazwa>Dodawanie</nazwa>
				<opis>Dodajemy</opis>
				<forma>Ćwiczenia</forma>
				<limit>10</limit>
			</kurs>
		</kierunek>
		</wydzial>
		
		<wydzial>
			<nazwa>Chemiczny</nazwa>
			
			<dziekan>
				<imie>Avcxzcxz</imie>
				<nazwisko>Afsdfsfsd</nazwisko>
				<tytul>profesor</tytul>
			</dziekan>
			
			<instytut>
				<nazwa>Kwasów</nazwa>
				<dyrektor>
					<tytul>profesor</tytul>
					<imie>Sylwia</imie>
					<nazwisko>Nowak</nazwisko>
				</dyrektor>
			</instytut>
			
			<kierunek>
				<nazwa>Fizyka</nazwa>
				<kurs>
					<nazwa>Wzory</nazwa>
					<opis>wzory fizyczne</opis>
					<forma>Wykłady</forma>
					<limit>10</limit>
				</kurs>
			</kierunek>
		</wydzial>
		
		<katedra>
			<nazwa>Gemometri</nazwa>
			<dyrektor>
				<tytul>profesor</tytul>
				<imie>dsadsadsadsa</imie>
				<nazwisko>vfvfdgfdgfdgfd</nazwisko>
			</dyrektor>
		</katedra>
</uczelnia>
